version: "3.9"

services:

  # Development container
  dev:
    build:
      context: .
      dockerfile: example_project/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/example_project
    tty: true
    stdin_open: true
    command: "/bin/bash"
